# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nro', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('foto', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='RegimenTenencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='regimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.RegimenTenencia'),
        ),
    ]
