# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='foto',
        ),
    ]
